<script lang="ts">
    import Narrow from '$lib/components/layout/narrow/Narrow.svelte';
</script>

<Narrow>
    {#if navigator.language === "ru-RU"}
        <p>Состояние деревьев в Ереване — тема, которая волнует многих. Но часто в обсуждениях не хватает объективных данных. Kanach Index создан, чтобы это исправить. Мы представляем комплексную оценку зелёного фонда города, основанную на прозрачной и проверяемой информации.</p>
        <p><strong>Откуда берутся данные?</strong> Основа индекса — это тысячи точек данных, собранных в поле неравнодушными горожанами с помощью нашего открытого приложения <a href="https://yerevan.treemaps.app/">Trees of Yerevan</a>. На сегодняшний день наша база содержит информацию о более чем 7000 деревьев.</p>
        <p>Важно понимать, что это лишь часть от сотен тысяч деревьев, растущих в Ереване. Однако существующая выборка уже достаточно велика и разнообразна, чтобы выявлять ключевые тенденции и делать первые осмысленные выводы о состоянии зелёного каркаса города. Точность и детализация Kanach Index напрямую зависят от полноты данных, и здесь нам нужна ваша помощь. Мы всегда рады волонтёрам, которые помогут нам наполнить базу. Каждое новое описанное дерево делает нашу общую картину города более точной.</p>
        <p><strong>Как это использовать?</strong> Kanach Index — это общественный инструмент. Для жителей — это способ понять, что происходит с зелёным каркасом города. Для активистов и журналистов — источник аргументов для публикаций и дискуссий. Для городских служб — независимый индикатор, который помогает оценивать эффективность их работы. Изучайте метрики ниже, чтобы увидеть, из чего складывается общая картина, и понять, какие аспекты требуют нашего общего внимания.</p>
    {:else}
        <p>The state of trees in Yerevan is a topic that concerns many. However, discussions often lack objective data. The Kanach Index was created to address this gap. We present a comprehensive assessment of the city's green assets based on transparent and verifiable information.</p>
        <p><strong>Where does the data come from?</strong> The foundation of the index is thousands of data points collected in the field by concerned citizens using our open application <a href="https://yerevan.treemaps.app/">Trees of Yerevan</a>. To date, our database contains information on over 7,000 trees.</p>
        <p>It is important to understand that this is only a fraction of the hundreds of thousands of trees growing in Yerevan. However, the existing sample is already large and diverse enough to identify key trends and make initial meaningful conclusions about the state of the city's green framework. The accuracy and detail of the Kanach Index directly depend on the completeness of the data, and we need your help here. We are always happy to welcome volunteers who can help us fill the database. Each newly described tree makes our overall picture of the city more accurate.</p>
        <p><strong>How to use it?</strong> The Kanach Index is a public tool. For residents, it is a way to understand what is happening with the city's green framework. For activists and journalists, it is a source of arguments for publications and discussions. For city services, it is an independent indicator that helps assess the effectiveness of their work. Explore the metrics below to see what makes up the overall picture and understand which aspects require our collective attention.</p>
    {/if}
</Narrow>
